# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr: none

variables:
  - group: Passwords
  - group: SoftwareVersions
  - group: SharepointPaths

resources:
  repositories:
  - repository: situm_capacitor_plugin
    type: github
    endpoint: SitumGithub
    name: situmtech/situm-capacitor-plugin-wayfinding
    ref: master

parameters:
  - name: XAPIEMAIL
    displayName: X-API-EMAIL
    type: string
    default: mrmqa@situm.es
  - name: XAPIKEY
    displayName: X-API-KEY
    type: string
    default: "<api-key>"
  - name: BUILDINGID
    displayName: BUILDINGID
    type: string
    default: 1


jobs:
  - job: Android_App
    pool:
      vmImage: $(ubuntuVersion)

    steps:
    - ${{ if ne(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY]$(echo $(XAPIKEY_EXAMPLES))"
           echo "##vso[task.setvariable variable=XAPIEMAIL]$(echo $(XAPIEMAIL_EXAMPLES))"
           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
        displayName: Configure Automatic run Vars

    - ${{ if eq(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY]$(echo ${{parameters.XAPIKEY}})"
           echo "##vso[task.setvariable variable=XAPIEMAIL]$(echo ${{ parameters.XAPIEMAIL}})"
           echo "##vso[task.setvariable variable=BUILDINGID]$(echo $(BUILDING_ID_EXAMPLES))"

           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
        displayName: Configure Manual run Vars

    - template: azure/common-steps.yaml
      parameters:
        system: "android"
        XAPIEMAIL: $(XAPIEMAIL)
        XAPIKEY: $(XAPIKEY)
        BUILDINGID: $(BUILDINGID)

    - template: azure/build-examples.yaml
      parameters:
        system: "ubuntu"


  - job: iOS_App
    pool:
      vmImage: $(macOSVersion)

    steps:

    - ${{ if ne(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY]$(echo $(XAPIKEY_EXAMPLES))"
           echo "##vso[task.setvariable variable=XAPIEMAIL]$(echo $(XAPIEMAIL_EXAMPLES))"
           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
        displayName: Configure Automatic run Vars

    - ${{ if eq(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY]$(echo ${{parameters.XAPIKEY}})"
           echo "##vso[task.setvariable variable=XAPIEMAIL]$(echo ${{ parameters.XAPIEMAIL}})"
           echo "##vso[task.setvariable variable=BUILDINGID]$(echo $(BUILDING_ID_EXAMPLES))"

           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
    
    - template: azure/common-steps.yaml
      parameters:
        system: "ios"
        XAPIEMAIL: $(XAPIEMAIL)
        XAPIKEY: $(XAPIKEY)
        BUILDINGID: $(BUILDINGID)


    - template: azure/build-examples.yaml
      parameters:
        system: "macOS"

