# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr: none

variables:
  - group: Passwords
  - group: SoftwareVersions
  - group: SharepointPaths

resources:
  repositories:
  - repository: situm_capacitor_plugin
    type: github
    endpoint: SitumGithub
    name: situmtech/situm-capacitor-plugin-wayfinding
    ref: master

parameters:
  - name: XAPIEMAIL
    displayName: X-API-EMAIL
    type: string
    default: mrmqa@situm.es
  - name: XAPIKEY
    displayName: X-API-KEY
    type: string
    default: "<api-key>"
  - name: BUILDINGID
    displayName: BUILDINGID
    type: string
    default: 1


jobs:
  - job: Set_Variables
    steps:
    - ${{ if ne(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY;isOutput=true;]$(echo $(XAPIKEY_EXAMPLES))"
           echo "##vso[task.setvariable variable=XAPIEMAIL;isOutput=true;]$(echo $(XAPIEMAIL_EXAMPLES))"
           echo "##vso[task.setvariable variable=BUILDINGID;isOutput=true;]$(echo $(BUILDING_ID_EXAMPLES))"
           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
        displayName: Configure Automatic run Vars
        name: setVariable

    - ${{ if eq(variables['Build.Reason'],'manual') }}:
      - bash: |
           echo "##vso[task.setvariable variable=XAPIKEY;isOutput=true;]$(echo ${{parameters.XAPIKEY}})"
           echo "##vso[task.setvariable variable=XAPIEMAIL;isOutput=true;]$(echo ${{parameters.XAPIEMAIL}})"
           echo "##vso[task.setvariable variable=BUILDINGID;isOutput=true;]$(echo ${{parameters.BUILDINGID}})"

           echo -e "\n[!] I'm a shy step so I don't show any information. You'll see my work in the Configure Credentials step"
        displayName: Configure Manual run Vars
        name: setVariable


  - job: Android_App
    dependsOn: ['Set_Variables']
    pool:
      vmImage: $(ubuntuVersion)
    variables:
      XAPIKEY: $[ dependencies.Set_Variables.outputs['setVariable.XAPIKEY']]
      XAPIEMAIL: $[ dependencies.Set_Variables.outputs['setVariable.XAPIEMAIL']]
      BUILDINGID: $[ dependencies.Set_Variables.outputs['setVariable.BUILDINGID']]
    steps: 
    - template: azure/common-steps.yaml
      parameters:
        system: "android"
        XAPIEMAIL: $(XAPIEMAIL)
        XAPIKEY: $(XAPIKEY)
        BUILDINGID: $(BUILDINGID)

    - template: azure/build-examples.yaml
      parameters:
        system: "ubuntu"


  - job: iOS_App
    dependsOn: ['Set_Variables']
    variables:
      XAPIKEY: $[dependencies.Set_Variables.outputs['setVariable.XAPIKEY']]
      XAPIEMAIL: $[dependencies.Set_Variables.outputs['setVariable.XAPIEMAIL']]
      BUILDINGID: $[dependencies.Set_Variables.outputs['setVariable.BUILDINGID']]
    pool:
      vmImage: $(macOSVersion)

    steps:
  
    - bash: |
         echo -e "\n[+] Install gnu-sed\n"
         brew install gnu-sed
      displayName: Install gnu-sed
    
    - template: azure/common-steps.yaml
      parameters:
        system: "ios"
        XAPIEMAIL: $(XAPIEMAIL)
        XAPIKEY: $(XAPIKEY)
        BUILDINGID: $(BUILDINGID)


    - template: azure/build-examples.yaml
      parameters:
        system: "macOS"

